export const ASSIGNE_VEHICLE_LIST = 'ASSIGNE_VEHICLE_LIST';
export const ASSIGNE_COPYVEHICLE_LIST = 'ASSIGNE_COPYVEHICLE_LIST';
export const DELETE_ITEM_FROM_VEHICLELIST = 'DELETE_ITEM_FROM_VEHICLELIST';
export const DELETE_ITEM_FROM_COPYVEHICLELIST = 'DELETE_ITEM_FROM_COPYVEHICLELIST';
export const ADD_ITEM_TO_VEHICLELIST = 'ADD_ITEM_TO_VEHICLELIST';
export const ADD_ITEM_TO_COPYVEHICLELIST = 'ADD_ITEM_TO_COPYVEHICLELIST';